### ISSUE TITLE
Migrate to Jest

### ISSUE THREAD

**Issue by arodik** [readdle/ffbt#15]

**Comment by turbo-lover** [comment]
I think we need to provide for the user an opportunity to choose test-framework

**Comment by arodik** [comment]
Sorry but no, it's our tool and we are free to decide which framework to use. Jest is a standard in 2k18, and it's actively maintained, so I'll migrate the Karma+Jasmine to more fast, stable and easy to use library (Jest)

**Comment by arodik** [comment]
Decided to entirely remove the testing framework from FFBT. You can add tests via Jest easily
